FROM rust:1.91.1-alpine AS builder
ENV CARGO_INCREMENTAL=0
ARG SQLX_VERSION
RUN apk add libc-dev
RUN cargo install sqlx-cli \
    --version ${SQLX_VERSION} \
    --locked \
    --no-default-features --features rustls,postgres

FROM alpine:3.22.2
ARG SQLX_VERSION=unknown
ARG GIT_REVISION=unknown
LABEL revision=${GIT_REVISION}
LABEL sqlx_version=${SQLX_VERSION}
COPY --from=builder /usr/local/cargo/bin/sqlx /sqlx
COPY db /migrations
ENTRYPOINT ["/sqlx"]
