FROM rust:1.60.0-alpine as builder
RUN apk add libc-dev

WORKDIR /src
COPY Cargo.toml /src/Cargo.toml
COPY Cargo.lock /src/Cargo.lock
COPY janus_server /src/janus_server
COPY monolithic_integration_test /src/monolithic_integration_test
COPY test_util /src/test_util
RUN --mount=type=cache,target=/usr/local/cargo/registry --mount=type=cache,target=/src/target cargo build --release --bin aggregation_job_creator && cp /src/target/release/aggregation_job_creator /aggregation_job_creator

FROM alpine:3.15.4
COPY --from=builder /aggregation_job_creator /aggregation_job_creator
ENTRYPOINT ["/aggregation_job_creator"]
