DROP INDEX outstanding_batches_task_and_time_bucket_index;
DROP TABLE outstanding_batches CASCADE;
DROP INDEX aggregate_share_jobs_interval_containment_index CASCADE;
DROP TABLE aggregate_share_jobs CASCADE;
DROP INDEX collection_jobs_interval_containment_index CASCADE;
DROP INDEX collection_jobs_state_and_lease_expiry CASCADE;
DROP INDEX collection_jobs_task_id_batch_id CASCADE;
DROP TABLE collection_jobs CASCADE;
DROP TYPE COLLECTION_JOB_STATE CASCADE;
DROP TABLE batch_aggregations CASCADE;
DROP TYPE BATCH_AGGREGATION_STATE;
DROP TABLE batches CASCADE;
DROP TYPE BATCH_STATE CASCADE;
DROP INDEX report_aggregations_client_report_id_index CASCADE;
DROP INDEX report_aggregations_aggregation_job_id_index CASCADE;
DROP TABLE report_aggregations CASCADE;
DROP TYPE REPORT_AGGREGATION_STATE CASCADE;
DROP INDEX aggregation_jobs_task_and_client_timestamp_interval CASCADE;
DROP INDEX aggregation_jobs_task_and_batch_id CASCADE;
DROP INDEX aggregation_jobs_state_and_lease_expiry CASCADE;
DROP TABLE aggregation_jobs CASCADE;
DROP TYPE AGGREGATION_JOB_STATE CASCADE;
DROP INDEX client_reports_task_and_timestamp_index CASCADE;
DROP INDEX client_reports_task_and_timestamp_unaggregated_index CASCADE;
DROP TABLE client_reports CASCADE;
DROP TABLE task_hpke_keys CASCADE;
DROP INDEX task_id_index CASCADE;
DROP TABLE tasks CASCADE;
DROP TABLE taskprov_aggregator_auth_tokens;
DROP TABLE taskprov_collector_auth_tokens;
DROP TABLE taskprov_peer_aggregators;
DROP TABLE global_hpke_keys;
DROP TYPE HPKE_KEY_STATE;
DROP TYPE AUTH_TOKEN_TYPE CASCADE;
DROP TYPE AGGREGATOR_ROLE CASCADE;
DROP EXTENSION btree_gist CASCADE;
DROP EXTENSION pgcrypto CASCADE;
